# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ccc1e9414271321c08fa2b6804c9ec41e5fe998ed69f95a67d13ec597ee0e5d13193aaad7a8e34bb434eab95c58d1bea592ead7de9077ba0a7230ec87c37679c

test:
  secret_key_base: 2da9ebf023435fdc076e4d267fef2cb956be83b052b55a2854b9368ec50f3a9623b25728a14c977d70168f65c30471d3087a65cb07699b0ccfbe2253dc4cb67a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
