# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3a0182003f93a7e5c73ed592c92e3afc5777d9e9a16077549f76c7334f67ac06acc0d24f208c18be3c4c26879bd4574051a3166019a628c430ac270eb3551dad

test:
  secret_key_base: 2a8c5cb48d17a65363e1b11f036c9f33e32fbacdfba588615f82ced1bd1de772f828e28d7c17e6931303014f4045599a838d77ce5e7a0b3c28838def171eca16

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
